version: '3'

services:

  app:
    container_name: constrspb_back
    build: 
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    volumes:
      - "../photos:/photos/"
    ports:
      - "12344:12344"